set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-pain-control'
set -g @plugin 'tmux-plugins/tmux-urlview'

# Bindings
bind r source-file ~/.tmux.conf
bind t new-window

# Options
set-option -g status-position top
set-option -g allow-rename off
set-option -g focus-events on # required by nvim

setw -g mouse on
setw -g base-index 1
setw -g pane-base-index 1
setw -g window-status-format ' #I:#W:#F '

set -sg escape-time 1 # quicker responses
set -s extended-keys on
set -as terminal-features 'xterm*:extkeys'

# Kanagawa Wave colors
bg=#1f1f28
fg=#dcd7ba
muted_text=#54546d
highlight=#7e9cd8
accent=#98bb6c

status_bg=#16161d
left_status_bg=#98bb6c
left_status_fg=#1f1f28

# Status bar
set -g status-style bg='#{status_bg}',fg='#{muted_text}'
set -g status-left '#[bg=#{left_status_bg},fg=#{left_status_fg},bold] #{session_name} #[bg=#{status_bg},fg=#{left_status_bg}]'
set -g status-right ''
set -g status-right-length 0
set -g status-left-length 0
setw -g window-status-current-style bg=$status_bg,fg='#{muted_text}'
setw -g window-status-separator '#[fg=#2a2a37]╲'
setw -g window-status-current-format ' \
#[fg=#{highlight}]#I \
#[fg=#{fg}]#W#[fg=#{highlight}]\
#{?window_zoomed_flag, 󰚀 ,}#{?pane_marked,󅊊 ,#{?pane_marked_set,󰀌 ,}}'

# Pane borders
set -g pane-border-style fg='#2a2a37'
set -g pane-active-border-style fg='#54546d'

# Messages & command prompt
set -g message-style bg='#2a2a37',fg='#dcd7ba'
set -g message-command-style bg='#2a2a37',fg='#dcd7ba'

# Selection / copy mode
set -g mode-style bg='#2d4f67',fg='#c8c093'

# Initialize TMUX plugin manager (keep this line at the very bottom)
run '~/.tmux/plugins/tpm/tpm'
